### ISSUE TITLE
怎么将inception-score应用到自己的测试图片上？

### ISSUE THREAD

**Issue by IPNUISTlegal** [tsc2017/inception-score#1]
同学，我是TensorFlow 1.8版本。之前用原作者的程序会报错，看你留言tf 1.6+能用。
现在运行程序显示
>> Downloading http://download.tensorflow.org/models/frozen_inception_v1_2015_12_05.tar.gz 63.3%
我是新手，不知道如何改程序才能应用到自己的36张256*256的测试图片上。谢谢

**Comment by tsc2017** [comment]
Hi there, I have added some guidelines for using this code
