### ISSUE TITLE
Is resizing images not required?

### ISSUE THREAD

**Issue by akanimax** [tsc2017/inception-score#3]
Hi @tsc2017,

I have gone through your code, and I find that you are not resizing the input images before calculating their activation scores from the InceptionNet. 
I found your repo from this discussion at https://github.com/openai/improved-gan/issues/29
For some reason, I am not getting correct IS value from this repo, so was looking for other codes and found this one.
Could you please let me know if the function requires resized images to size [229 x 229 x 3] is it okay to send it [32 x 32 x 3] CIFAR-10 images?

Best regards,
@akanimax

**Comment by tsc2017** [comment]
No, you can just call `get_inception_score(images, splits=10)`, where `images` is a numpy array with values ranging from 0 to 255 and shape in the form `[N, 3, HEIGHT, WIDTH]` where `N`, `HEIGHT` and `WIDTH` can be arbitrary.

**Comment by akanimax** [comment]
Ok Thanks! BTW, I am getting error related to dtype. Expected dtype for placeholder is `float`. Could you please help how to solve it?

**Comment by tsc2017** [comment]
So which placeholder are you referring to? I think you do not have to deal with placeholders directly.

**Comment by akanimax** [comment]
Thank you for the code. The problem was solved. 
Also thank you for your help.

Best regards,
@akanimax
