### ISSUE TITLE
http error 409： conflict

### ISSUE THREAD

**Issue by lucky1177214** [tsc2017/inception-score#4]
INCEPTION_URL = "http://download.tensorflow.org/models/frozen_inception_v1_2015_12_05.tar.gz"

tfgan.eval.get_graph_def_from_url_tarball(url=INCEPTION_URL,filename=INCEPTION_FROZEN_GRAPH,tar_filename=os.path.basename(INCEPTION_URL))

执行上述代码会出现 http error 409： conflict

**Comment by lucky1177214** [comment]
@tsc2017 
I ask for your help, thanks

**Comment by tsc2017** [comment]
Hi, you can just download this file and put in the same directory as your code does.

**Comment by lucky1177214** [comment]
@tsc2017 
hi ，I open URL, then I get the following problem 

Please enable cookies.
Error 1001 Ray ID: 54580db10c0b779a • 2019-12-15 11:24:50 UTC
DNS resolution error
What happened?
You've requested a page on a website (download.tensorflow.org) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (download.tensorflow.org). There are two potential causes of this:

Most likely: if the owner just signed up for Cloudflare it can take a few minutes for the website's information to be distributed to our global network.
Less likely: something is wrong with this site's configuration. Usually this happens when accounts have been signed up with a partner organization (e.g., a hosting provider) and the provider's DNS fails.
Cloudflare Ray ID: 54580db10c0b779a • Your IP: 221.212.176.32 • Performance & security by Cloudflare

**Comment by lucky1177214** [comment]
@tsc2017 
hello， I use the campus network， wireless。

**Comment by tsc2017** [comment]
@lucky1177214 
The URL works fine for me. Maybe you should try and download with a different Internet connection.

**Comment by lucky1177214** [comment]
@tsc2017 
Thank you for your suggestion very much , the problem has been solved！
