### ISSUE TITLE
CIFAR-10 results not correct.

### ISSUE THREAD

**Issue by cientgu** [tsc2017/inception-score#5]
Hi, i test CIFAR-10 50000 training images using your get_inception_score, but the results is only about 9(mean) for 1 split. Your mentioned you get the results over 11. I have check the input numpy is in the range of [0,255] and shape of [50000,3,32,32], i am not sure why. So could you provide the dataloader part to help my testing?

**Comment by tsc2017** [comment]
Hi, you may want to refer to this example:
https://github.com/tsc2017/Inception-Score/blob/master/README.md#example

**Comment by cientgu** [comment]
> Hi, you may want to refer to this example:
> https://github.com/tsc2017/Inception-Score/blob/master/README.md#example

Thank you for your reply, i found the reason is i haven't reshuffle the training data so each split is not random. After that, i got a similar IS.
